user  nginx;
worker_processes  auto;

events {
    worker_connections  512;
}

http {
    sendfile on;

    # --- 添加这个 UPSTREAM 块 ---
    upstream php-upstream {
        server php:9000;
    }
    # ---------------------------------

    server {
        listen 80;
        server_name localhost;

        root /var/www/html/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?s=$uri&$args;
        }

        location ~ \.php$ {
            # --- 更改这一行 ---
            fastcgi_pass php-upstream;
            # --------------------
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}
